package vista;

import java.awt.event.FocusEvent;
import java.util.ArrayList;

import java.util.List;
import javax.swing.JComboBox;
import modelo.ModeloTablaGenerico;
import utilidades.InvalidException;
import utilidades.Utilidades;

/**
 *
 * @author Kymera Systems SAS
 */
public class DescuentoVista extends VentanaInternaAbs {

    private FachadaInterfaz fachada;
    private String[] nomTablaVentas = {"PRODUCTO", "DESCUENTO"};

    /** Creates new form DescuentoVista */
    public DescuentoVista() {
        initComponents();
        fachada = FachadaInterfaz.getInstancia();
        ModeloTablaGenerico generico = new ModeloTablaGenerico();
        generico.establecerColumNom(nomTablaVentas);
        tablaDescuento.setModel(generico);
        if (control.PuntoDeVenta.usuarioActual.getPermisos() != control.PuntoDeVenta.CAJERO) {
            System.out.println("entro l descuento");
            cargarComboProducto(cbxProducto);
            cargarComboCategoria(cbxCategoria);
            cargarComboProducto(cbxProd);
            cargarComboCategoria(cbxCategoriaCliente);
            cargarComboCliente();
        } else {
            this.tbpDescuento.setEnabledAt(0, false);
            this.tbpDescuento.setEnabledAt(1, false);
            this.tbpDescuento.setEnabledAt(2, false);
            this.tbpDescuento.setSelectedIndex(3);
        }
    }

    public void cargarComboProducto(JComboBox combo) {
        combo.setModel(new ModeloCombo(fachada.getProductos()));
        combo.getModel().setSelectedItem("Seleccione Producto...");
        combo.updateUI();
    }

    public void cargarComboCategoria(JComboBox combo) {
        combo.setModel(new ModeloCombo(fachada.getCategoria()));
        combo.getModel().setSelectedItem("Seleccione Categoria...");
        combo.updateUI();
    }

    public void cargarComboCliente() {
        cbxCliente.setModel(new ModeloCombo(fachada.getCliente()));
        cbxCliente.getModel().setSelectedItem("Seleccione Cliente...");
        cbxCliente.updateUI();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grpChek = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        tbpDescuento = new javax.swing.JTabbedPane();
        pnlPorFecha = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        hFinal = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        mFinal = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        dtcInicial = new com.toedter.calendar.JDateChooser();
        dtcFinal = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        hInicial = new javax.swing.JSpinner();
        mInicial = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtDesPro = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cbxProducto = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        chkActivo = new javax.swing.JRadioButton();
        chkInactivo = new javax.swing.JRadioButton();
        btnGuardar = new javax.swing.JButton();
        pnlCategorias = new javax.swing.JPanel();
        btnGuarPro = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        hFinal1 = new javax.swing.JSpinner();
        jLabel12 = new javax.swing.JLabel();
        mFinal1 = new javax.swing.JSpinner();
        jLabel13 = new javax.swing.JLabel();
        dtcInicial1 = new com.toedter.calendar.JDateChooser();
        dtcFinal1 = new com.toedter.calendar.JDateChooser();
        jLabel14 = new javax.swing.JLabel();
        hInicial1 = new javax.swing.JSpinner();
        mInicial1 = new javax.swing.JSpinner();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtDesCat = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        cbxCategoria = new javax.swing.JComboBox();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        chkActivo1 = new javax.swing.JRadioButton();
        chkInactivo1 = new javax.swing.JRadioButton();
        pnlClientes = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        lblProducto = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        txtDesClie = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        cbxCliente = new javax.swing.JComboBox();
        jLabel29 = new javax.swing.JLabel();
        cbxProd = new javax.swing.JComboBox();
        lblCategoria = new javax.swing.JLabel();
        cbxCategoriaCliente = new javax.swing.JComboBox();
        jLabel23 = new javax.swing.JLabel();
        rdbProducto = new javax.swing.JRadioButton();
        rdbCategoria = new javax.swing.JRadioButton();
        dtcInicial2 = new com.toedter.calendar.JDateChooser();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        dtcFinal2 = new com.toedter.calendar.JDateChooser();
        jLabel24 = new javax.swing.JLabel();
        hInicial2 = new javax.swing.JSpinner();
        mInicial2 = new javax.swing.JSpinner();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        hFinal2 = new javax.swing.JSpinner();
        jLabel30 = new javax.swing.JLabel();
        mFinal2 = new javax.swing.JSpinner();
        jLabel31 = new javax.swing.JLabel();
        chkActivo2 = new javax.swing.JRadioButton();
        chkInactivo2 = new javax.swing.JRadioButton();
        btnGuardarClie = new javax.swing.JButton();
        pnlLista = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaDescuento = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Descuento Por Producto"));

        jLabel1.setText("Fecha Inicial:");

        jLabel2.setText("Fecha Final:");

        hFinal.setModel(new javax.swing.SpinnerNumberModel(24, 1, 24, 1));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Hora Inicial:");

        mFinal.setModel(new javax.swing.SpinnerNumberModel(0, 0, 45, 15));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel4.setText(":");

        jLabel5.setText("Hora Final:");

        hInicial.setModel(new javax.swing.SpinnerNumberModel(8, 1, 24, 1));

        mInicial.setModel(new javax.swing.SpinnerNumberModel(0, 0, 45, 15));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel6.setText(":");

        jLabel8.setText("Descuento:");

        txtDesPro.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDesPro.setText("0");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel9.setText("%");

        cbxProducto.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione Producto..." }));

        jLabel7.setText("Producto:");

        jLabel19.setText("Estado");

        grpChek.add(chkActivo);
        chkActivo.setSelected(true);
        chkActivo.setText("Activo");

        grpChek.add(chkInactivo);
        chkInactivo.setText("Inactivo");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel19)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkActivo)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cbxProducto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(hInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(mInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(16, 16, 16))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(hFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(mFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(dtcFinal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(dtcInicial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(txtDesPro, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel9)))
                            .addComponent(chkInactivo))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(cbxProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(dtcInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dtcFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(mInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(mFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDesPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(chkActivo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkInactivo))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel19)))
                .addContainerGap())
        );

        btnGuardar.setMnemonic('G');
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlPorFechaLayout = new javax.swing.GroupLayout(pnlPorFecha);
        pnlPorFecha.setLayout(pnlPorFechaLayout);
        pnlPorFechaLayout.setHorizontalGroup(
            pnlPorFechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPorFechaLayout.createSequentialGroup()
                .addGroup(pnlPorFechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPorFechaLayout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(btnGuardar))
                    .addGroup(pnlPorFechaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlPorFechaLayout.setVerticalGroup(
            pnlPorFechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPorFechaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(btnGuardar)
                .addContainerGap())
        );

        tbpDescuento.addTab("Producto", pnlPorFecha);

        btnGuarPro.setMnemonic('G');
        btnGuarPro.setText("Guardar");
        btnGuarPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuarProActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Descuento Por Categoria"));

        jLabel10.setText("Fecha Inicial:");

        jLabel11.setText("Fecha Final:");

        hFinal1.setModel(new javax.swing.SpinnerNumberModel(24, 1, 24, 1));

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setText("Hora Inicial:");

        mFinal1.setModel(new javax.swing.SpinnerNumberModel(0, 0, 45, 15));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel13.setText(":");

        jLabel14.setText("Hora Final:");

        hInicial1.setModel(new javax.swing.SpinnerNumberModel(8, 1, 24, 1));

        mInicial1.setModel(new javax.swing.SpinnerNumberModel(0, 0, 45, 15));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel15.setText(":");

        jLabel16.setText("Descuento:");

        txtDesCat.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDesCat.setText("0");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel17.setText("%");

        cbxCategoria.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione Categoria..." }));

        jLabel18.setText("Categoria:");

        jLabel20.setText("Estado");

        buttonGroup1.add(chkActivo1);
        chkActivo1.setText("Activo");

        buttonGroup1.add(chkInactivo1);
        chkInactivo1.setText("Inactivo");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                        .addComponent(cbxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel10)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel14)
                            .addComponent(jLabel16)
                            .addComponent(jLabel20))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(chkActivo1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chkInactivo1))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(hInicial1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(mInicial1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(dtcFinal1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(dtcInicial1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(txtDesCat, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel17))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(hFinal1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel13)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(mFinal1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel18)
                    .addComponent(cbxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(dtcInicial1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel11)
                        .addGap(20, 20, 20)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel16))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dtcFinal1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hInicial1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)
                            .addComponent(mInicial1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hFinal1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(mFinal1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDesCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(chkInactivo1)
                        .addComponent(chkActivo1))
                    .addComponent(jLabel20))
                .addContainerGap(90, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlCategoriasLayout = new javax.swing.GroupLayout(pnlCategorias);
        pnlCategorias.setLayout(pnlCategoriasLayout);
        pnlCategoriasLayout.setHorizontalGroup(
            pnlCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCategoriasLayout.createSequentialGroup()
                .addGroup(pnlCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCategoriasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlCategoriasLayout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(btnGuarPro)))
                .addContainerGap())
        );
        pnlCategoriasLayout.setVerticalGroup(
            pnlCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCategoriasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnGuarPro)
                .addContainerGap())
        );

        tbpDescuento.addTab("Categorias", pnlCategorias);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Descuento Por Cliente:"));

        lblProducto.setText("Producto:");

        jLabel27.setText("Descuento:");

        txtDesClie.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDesClie.setText("0");

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel28.setText("%");

        cbxCliente.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione Cliente..." }));

        jLabel29.setText("Cliente:");

        cbxProd.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione Producto..." }));

        lblCategoria.setText("Categoria:");
        lblCategoria.setEnabled(false);

        cbxCategoriaCliente.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione Categoria..." }));
        cbxCategoriaCliente.setEnabled(false);

        jLabel23.setText("Descuento Aplicado a:");

        buttonGroup2.add(rdbProducto);
        rdbProducto.setSelected(true);
        rdbProducto.setText("Producto");
        rdbProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbProductoActionPerformed(evt);
            }
        });

        buttonGroup2.add(rdbCategoria);
        rdbCategoria.setText("Categoria");
        rdbCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbCategoriaActionPerformed(evt);
            }
        });

        jLabel21.setText("Fecha Inicial:");

        jLabel22.setText("Fecha Final:");

        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel24.setText("Hora Inicial:");

        hInicial2.setModel(new javax.swing.SpinnerNumberModel(8, 1, 24, 1));

        mInicial2.setModel(new javax.swing.SpinnerNumberModel(0, 0, 45, 15));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel25.setText(":");

        jLabel26.setText("Hora Final:");

        hFinal2.setModel(new javax.swing.SpinnerNumberModel(24, 1, 24, 1));

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel30.setText(":");

        mFinal2.setModel(new javax.swing.SpinnerNumberModel(0, 0, 45, 15));

        jLabel31.setText("Estado");

        buttonGroup1.add(chkActivo2);
        chkActivo2.setSelected(true);
        chkActivo2.setText("Activo");

        buttonGroup1.add(chkInactivo2);
        chkInactivo2.setText("Inactivo");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lblProducto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                        .addComponent(cbxProd, 0, 139, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addComponent(jLabel29))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(cbxCliente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rdbCategoria)
                                    .addComponent(rdbProducto))
                                .addGap(74, 74, 74))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(lblCategoria)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(dtcFinal2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(dtcInicial2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cbxCategoriaCliente, javax.swing.GroupLayout.Alignment.TRAILING, 0, 139, Short.MAX_VALUE))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22))
                .addContainerGap(239, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                .addComponent(txtDesClie, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel28)
                .addGap(84, 84, 84))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel31)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                        .addComponent(chkActivo2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkInactivo2))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24)
                            .addComponent(jLabel26))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(hInicial2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel25)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(mInicial2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                .addComponent(hFinal2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel30)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(mFinal2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(43, 43, 43))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel29)
                    .addComponent(cbxCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addGap(27, 27, 27))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(rdbProducto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdbCategoria)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProducto)
                    .addComponent(cbxProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxCategoriaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCategoria))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel21)
                        .addGap(17, 17, 17)
                        .addComponent(jLabel22))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dtcInicial2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dtcFinal2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel26)
                        .addGap(7, 7, 7))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hInicial2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25)
                            .addComponent(mInicial2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hFinal2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel30)
                            .addComponent(mFinal2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(txtDesClie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkInactivo2)
                    .addComponent(chkActivo2)
                    .addComponent(jLabel31))
                .addGap(9, 9, 9))
        );

        btnGuardarClie.setText("Guardar");
        btnGuardarClie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarClieActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlClientesLayout = new javax.swing.GroupLayout(pnlClientes);
        pnlClientes.setLayout(pnlClientesLayout);
        pnlClientesLayout.setHorizontalGroup(
            pnlClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlClientesLayout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(btnGuardarClie)
                .addContainerGap(149, Short.MAX_VALUE))
            .addGroup(pnlClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );
        pnlClientesLayout.setVerticalGroup(
            pnlClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGuardarClie)
                .addContainerGap())
        );

        tbpDescuento.addTab("Clientes", pnlClientes);

        tablaDescuento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaDescuento);

        jButton1.setText("Ver Descuentos Activos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlListaLayout = new javax.swing.GroupLayout(pnlLista);
        pnlLista.setLayout(pnlListaLayout);
        pnlListaLayout.setHorizontalGroup(
            pnlListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlListaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlListaLayout.setVerticalGroup(
            pnlListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlListaLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );

        tbpDescuento.addTab("Lista Descuentos", pnlLista);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tbpDescuento, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tbpDescuento, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        ArrayList datos = new ArrayList();
        String idProd = (String) ((ModeloCombo) cbxProducto.getModel()).getSelectedIndex();
        String desc = txtDesPro.getText();
        String fecIni = Utilidades.datetoStringLimpio(dtcInicial.getDate());
        String fecFin = Utilidades.datetoStringLimpio(dtcFinal.getDate());
        int hIni, mIni, hFin, mFin;
        String estado;
        hIni = (Integer) hInicial.getValue();
        mIni = (Integer) mInicial.getValue();
        String horIni = hIni + ":" + mIni;
        hFin = (Integer) hFinal.getValue();
        mFin = (Integer) mFinal.getValue();
        String horFin = hFin + ":" + mFin;
        if (chkActivo.isSelected()) {
            estado = "Activo";
        } else {
            estado = "Inactivo";
        }
        datos.add(idProd);
        datos.add(desc);
        datos.add("0");
        datos.add(fecIni);
        datos.add(fecFin);
        datos.add(horIni);
        datos.add(horFin);
        datos.add(estado);
        fachada.descuentos(datos, FachadaInterfaz.INSERTAR);
        MenuVista.setInternal(3);
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnGuarProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuarProActionPerformed
        ArrayList datos = new ArrayList();
        String idCategoria = (String) ((ModeloCombo) this.cbxCategoria.getModel()).getSelectedIndex();
        String desc = txtDesCat.getText();
        String fecIni = Utilidades.datetoStringLimpio(dtcInicial1.getDate());
        String fecFin = Utilidades.datetoStringLimpio(dtcFinal1.getDate());
        int hIni, mIni, hFin, mFin;
        String estado;
        hIni = (Integer) hInicial1.getValue();
        mIni = (Integer) mInicial1.getValue();
        String horIni = hIni + ":" + mIni;
        hFin = (Integer) hFinal1.getValue();
        mFin = (Integer) mFinal1.getValue();
        String horFin = hFin + ":" + mFin;
        if (chkActivo1.isSelected()) {
            estado = "Activo";
        } else {
            estado = "Inactivo";
        }

        datos.add(idCategoria);
        datos.add(desc);
        datos.add("0");
        datos.add(fecIni);
        datos.add(fecFin);
        datos.add(horIni);
        datos.add(horFin);
        datos.add(estado);
        fachada.descuentosxCateg(datos, FachadaInterfaz.INSERTAR);
        MenuVista.setInternal(3);
    }//GEN-LAST:event_btnGuarProActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            cargarTabla(fachada.getDescuentosDia());
        } catch (InvalidException ex) {
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void rdbCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbCategoriaActionPerformed
        lblCategoria.setEnabled(true);
        cbxCategoriaCliente.setEnabled(true);
        cbxProd.setEnabled(false);
        lblProducto.setEnabled(false);
    }//GEN-LAST:event_rdbCategoriaActionPerformed

    private void rdbProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbProductoActionPerformed
        lblCategoria.setEnabled(false);
        cbxCategoriaCliente.setEnabled(false);
        cbxProd.setEnabled(true);
        lblProducto.setEnabled(true);
    }//GEN-LAST:event_rdbProductoActionPerformed

    private void btnGuardarClieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarClieActionPerformed
        ArrayList datos = new ArrayList();
        String idCliente =  (String)((ModeloCombo)cbxCliente.getModel()).getSelectedIndex();
        String idCombo = "";
        if(rdbProducto.isSelected()){
            idCombo = (String) ((ModeloCombo) this.cbxProd.getModel()).getSelectedIndex();
        }else{
            idCombo = (String) ((ModeloCombo) this.cbxCategoriaCliente.getModel()).getSelectedIndex();
        }
        String desc = txtDesClie.getText();
        String fecIni = Utilidades.datetoStringLimpio(dtcInicial2.getDate());
        String fecFin = Utilidades.datetoStringLimpio(dtcFinal2.getDate());
        int hIni, mIni, hFin, mFin;
        String estado;
        hIni = (Integer) hInicial2.getValue();
        mIni = (Integer) mInicial2.getValue();
        String horIni = hIni + ":" + mIni;
        hFin = (Integer) hFinal2.getValue();
        mFin = (Integer) mFinal2.getValue();
        String horFin = hFin + ":" + mFin;
        if (chkActivo2.isSelected()) {
            estado = "Activo";
        } else {
            estado = "Inactivo";
        }
        datos.add(idCombo);
        datos.add(desc);
        datos.add(idCliente);
        datos.add(fecIni);
        datos.add(fecFin);
        datos.add(horIni);
        datos.add(horFin);
        datos.add(estado);
        if(rdbProducto.isSelected()){
            fachada.descuentos(datos, FachadaInterfaz.INSERTAR);
        }else{
            fachada.descuentosxCateg(datos, FachadaInterfaz.INSERTAR);
        }
        MenuVista.setInternal(3);
    }//GEN-LAST:event_btnGuardarClieActionPerformed

    public void cargarTabla(List datos) {
        ModeloTablaGenerico generico = new ModeloTablaGenerico(datos);
        generico.establecerColumNom(nomTablaVentas);
        tablaDescuento.setModel(generico);
        tablaDescuento.updateUI();
        this.updateUI();
    }

    @Override
    public void establecerFoco() {
    }

    @Override
    public void setFocoGanado(FocusEvent evt) {
    }

    @Override
    public void setFocoPerdido(FocusEvent evt) {
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuarPro;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnGuardarClie;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox cbxCategoria;
    private javax.swing.JComboBox cbxCategoriaCliente;
    private javax.swing.JComboBox cbxCliente;
    private javax.swing.JComboBox cbxProd;
    private javax.swing.JComboBox cbxProducto;
    private javax.swing.JRadioButton chkActivo;
    private javax.swing.JRadioButton chkActivo1;
    private javax.swing.JRadioButton chkActivo2;
    private javax.swing.JRadioButton chkInactivo;
    private javax.swing.JRadioButton chkInactivo1;
    private javax.swing.JRadioButton chkInactivo2;
    private com.toedter.calendar.JDateChooser dtcFinal;
    private com.toedter.calendar.JDateChooser dtcFinal1;
    private com.toedter.calendar.JDateChooser dtcFinal2;
    private com.toedter.calendar.JDateChooser dtcInicial;
    private com.toedter.calendar.JDateChooser dtcInicial1;
    private com.toedter.calendar.JDateChooser dtcInicial2;
    private javax.swing.ButtonGroup grpChek;
    private javax.swing.JSpinner hFinal;
    private javax.swing.JSpinner hFinal1;
    private javax.swing.JSpinner hFinal2;
    private javax.swing.JSpinner hInicial;
    private javax.swing.JSpinner hInicial1;
    private javax.swing.JSpinner hInicial2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCategoria;
    private javax.swing.JLabel lblProducto;
    private javax.swing.JSpinner mFinal;
    private javax.swing.JSpinner mFinal1;
    private javax.swing.JSpinner mFinal2;
    private javax.swing.JSpinner mInicial;
    private javax.swing.JSpinner mInicial1;
    private javax.swing.JSpinner mInicial2;
    private javax.swing.JPanel pnlCategorias;
    private javax.swing.JPanel pnlClientes;
    private javax.swing.JPanel pnlLista;
    private javax.swing.JPanel pnlPorFecha;
    private javax.swing.JRadioButton rdbCategoria;
    private javax.swing.JRadioButton rdbProducto;
    private javax.swing.JTable tablaDescuento;
    private javax.swing.JTabbedPane tbpDescuento;
    private javax.swing.JTextField txtDesCat;
    private javax.swing.JTextField txtDesClie;
    private javax.swing.JTextField txtDesPro;
    // End of variables declaration//GEN-END:variables
}
