package vista;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import modelo.ModeloTabla;
import utilidades.Impresion;
import utilidades.Utilidades;

/**
 *
 * @author Kymera Systems SAS
 */
public class OrdenVista extends javax.swing.JDialog {

    private String contenido, empresa, NIT,direccion,pagaCon,cambio,baseGrabable;
    private String producto, cantidad, valor, subtotal, total,descTotal,IVA,descuento;
    public boolean facturar;
    private CompraVista vista;
    private PagoOrden p;
    private Object[] tarifa;
    private int cont,tar;
    private double base,iva,baseT,ivaT;

    /** Creates new form FacturaVista */
    public OrdenVista(java.awt.Frame parent, boolean modal,PagoOrden p) {
        super(parent, modal);
        initComponents();
        this.p = p;
        lblEmpresa.setText(MenuVista.sigla);
        lblNIT.setText(MenuVista.Nit);
        lblDireccion.setText(MenuVista.direccion);
        lblRazonSocial.setText(MenuVista.razonSocial);
        lblUbicacion.setText(MenuVista.ciudad);

        lblProveedor.setText(FachadaInterfaz.getInstancia().ptoVenta.getNombreUsuarioActual());
        lblFechaE.setText(Utilidades.getHoraActual());
        lblFechaP.setText(Utilidades.datetoString(new Date()));
        this.setSize(460,649);
        this.setLocation(350, 70);

    }
    public OrdenVista(java.awt.Frame parent, boolean modal,CompraVista vista) {
        super(parent, modal);
        initComponents();
        this.vista = vista;
        
        lblEmpresa.setText(MenuVista.sigla);
        lblNIT.setText(MenuVista.Nit);
        lblDireccion.setText(MenuVista.direccion);
        lblRazonSocial.setText(MenuVista.razonSocial);
        lblUbicacion.setText(MenuVista.ciudad);

        lblProveedor.setText(FachadaInterfaz.getInstancia().ptoVenta.getNombreUsuarioActual());
        lblFechaE.setText(Utilidades.getHoraActual());
        lblFechaP.setText(Utilidades.datetoString(new Date()));
        this.setSize(460,649);
        this.setLocation(350, 70);

    }
    public void setContenido(List conten) {
        contenido = "";
        for (int i = 0; i < conten.size(); i++) {
            producto = (String) conten.get(i);
            cantidad = (String) conten.get(++i);
            valor = (String) conten.get(++i);
            subtotal = (String) conten.get(++i);
            if (producto.length() <= 15) {
                producto += "      ";
            } else if (producto.length() >= 20) {
                producto = producto.substring(0, 20);
            }
            contenido += producto + "\t" + cantidad + "\t" +
                    valor + "\t" + subtotal + "\n";
        }
        this.tatFactura.setText(contenido);
        tatFactura.append("\n\n\n\n\t\t\t                       ===========\n" +
                "Subtotal sin Descuento:\t\t\t\t"+vista.subTotal);
        tatFactura.append("\n**********************************************************\n");
        tatFactura.append("IVA      \t\t\t\t\t"+vista.iva+"\n");
        tatFactura.append("\t\t\t                       ===========\n" +
                "TOTAL A PAGAR \t\t\t\t\t"+vista.total+"\n");
        for(Double val: vista.imp.values()){
            tarifa = vista.imp.keySet().toArray();
            tar = (Integer)tarifa[cont];
            System.out.println("Valor Factra:" +val);
            base = Utilidades.getBaseGravable(val, tar);
            iva = Utilidades.getValorIva(val, tar);
            tatImpuesto.append("      "+tar+"%     "+"\t\t"+
                    Utilidades.darFormatoNumero(base)+
                    "\t\t"+Utilidades.darFormatoNumero(iva)+"\n");
            baseT += base;
            ivaT += iva;
            cont++;
        }
        tatImpuesto.append("            \t                       =============\t                       ===========\n");
        tatImpuesto.append("   TOTAL       \t\t"+Utilidades.darFormatoNumero(baseT)+
                "\t\t"+Utilidades.darFormatoNumero(ivaT)+"\n");
        this.setVisible(true);

    }
    public void guardarCompra(){
        FachadaInterfaz.getInstancia().terminarCompra();
        dispose();
    }
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        pnlConten = new javax.swing.JPanel();
        tatFactura = new javax.swing.JTextArea();
        lblRazonSocial = new javax.swing.JLabel();
        lblNIT = new javax.swing.JLabel();
        lblEmpresa = new javax.swing.JLabel();
        lblUbicacion = new javax.swing.JLabel();
        lblDireccion = new javax.swing.JLabel();
        labelProv = new javax.swing.JLabel();
        lblProveedor = new javax.swing.JLabel();
        lblFechaP = new javax.swing.JLabel();
        lblFechaEntre = new javax.swing.JLabel();
        labelFechaPedi = new javax.swing.JLabel();
        lblFechaE = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblItems = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tatImpuesto = new javax.swing.JTextArea();
        pnlBotones = new javax.swing.JPanel();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        pnlConten.setBackground(new java.awt.Color(254, 254, 254));
        pnlConten.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED)));

        tatFactura.setBackground(new java.awt.Color(254, 254, 254));
        tatFactura.setColumns(20);
        tatFactura.setEditable(false);
        tatFactura.setFont(new java.awt.Font("Monospaced", 0, 12));
        tatFactura.setRows(5);
        tatFactura.setText("SMVS,\nSADFKLSADF\nDSJLSDF\nJLSDFJLDS\nJSDJLSD\nSDKGJLS\nSDJKFLS\nSJDKL\nJL\nSDF");
        tatFactura.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        lblRazonSocial.setFont(new java.awt.Font("Tahoma", 0, 12));
        lblRazonSocial.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRazonSocial.setText("RAZON SOCIAL");

        lblNIT.setFont(new java.awt.Font("Tahoma", 0, 12));
        lblNIT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNIT.setText("NIT");

        lblEmpresa.setFont(new java.awt.Font("Tahoma", 0, 12));
        lblEmpresa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEmpresa.setText("EMPRESA");

        lblUbicacion.setFont(new java.awt.Font("Tahoma", 0, 12));
        lblUbicacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUbicacion.setText("UBICACION");

        lblDireccion.setFont(new java.awt.Font("Tahoma", 0, 12));
        lblDireccion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDireccion.setText("DIRECCION");

        labelProv.setFont(new java.awt.Font("Tahoma", 0, 12));
        labelProv.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelProv.setText("Proveedor:");

        lblProveedor.setFont(new java.awt.Font("Tahoma", 0, 12));
        lblProveedor.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblProveedor.setText("Juan Fernando Escobar");

        lblFechaP.setFont(new java.awt.Font("Tahoma", 0, 12));
        lblFechaP.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblFechaP.setText("FECHA PEDIDO");

        lblFechaEntre.setFont(new java.awt.Font("Tahoma", 0, 12));
        lblFechaEntre.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblFechaEntre.setText("Fecha Entrega:");

        labelFechaPedi.setFont(new java.awt.Font("Tahoma", 0, 12));
        labelFechaPedi.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelFechaPedi.setText("Fecha Pedido:");

        lblFechaE.setFont(new java.awt.Font("Tahoma", 0, 12));
        lblFechaE.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblFechaE.setText("FECHA ENTREGA");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel2.setText("PRODUCTO");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel3.setText("CANTIDAD");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel4.setText("PRECIO COS");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("SUBTOTAL");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("DETALLE DE IMPUESTOS");

        lblItems.setFont(new java.awt.Font("Tahoma", 0, 12));
        lblItems.setText("ITEMS COMPRADOS:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("TARIFA");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("BASE");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("IVA");

        jScrollPane2.setBackground(new java.awt.Color(254, 254, 254));
        jScrollPane2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        tatImpuesto.setBackground(new java.awt.Color(254, 254, 254));
        tatImpuesto.setColumns(20);
        tatImpuesto.setEditable(false);
        tatImpuesto.setRows(5);
        tatImpuesto.setBorder(null);
        jScrollPane2.setViewportView(tatImpuesto);

        javax.swing.GroupLayout pnlContenLayout = new javax.swing.GroupLayout(pnlConten);
        pnlConten.setLayout(pnlContenLayout);
        pnlContenLayout.setHorizontalGroup(
            pnlContenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContenLayout.createSequentialGroup()
                .addGroup(pnlContenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlContenLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlContenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRazonSocial, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE)
                            .addComponent(lblNIT, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE)
                            .addComponent(lblEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE)
                            .addComponent(lblUbicacion, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE)
                            .addComponent(lblDireccion, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE)
                            .addGroup(pnlContenLayout.createSequentialGroup()
                                .addGroup(pnlContenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(labelFechaPedi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(labelProv, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnlContenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlContenLayout.createSequentialGroup()
                                        .addComponent(lblProveedor, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                                        .addGap(94, 94, 94))
                                    .addGroup(pnlContenLayout.createSequentialGroup()
                                        .addComponent(lblFechaP, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(2, 2, 2)
                                        .addComponent(lblFechaEntre, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblFechaE))))))
                    .addGroup(pnlContenLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel2)
                        .addGap(47, 47, 47)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE))
                    .addGroup(pnlContenLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tatFactura, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(pnlContenLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlContenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlContenLayout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(102, 102, 102)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlContenLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))
                    .addGroup(pnlContenLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblItems, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
                        .addGap(41, 41, 41)))
                .addGap(8, 8, 8))
        );
        pnlContenLayout.setVerticalGroup(
            pnlContenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContenLayout.createSequentialGroup()
                .addComponent(lblRazonSocial)
                .addGap(1, 1, 1)
                .addComponent(lblNIT)
                .addGap(1, 1, 1)
                .addComponent(lblEmpresa)
                .addGap(1, 1, 1)
                .addComponent(lblUbicacion)
                .addGap(1, 1, 1)
                .addComponent(lblDireccion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlContenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlContenLayout.createSequentialGroup()
                        .addComponent(labelProv)
                        .addGap(1, 1, 1)
                        .addComponent(labelFechaPedi))
                    .addGroup(pnlContenLayout.createSequentialGroup()
                        .addComponent(lblProveedor)
                        .addGap(1, 1, 1)
                        .addGroup(pnlContenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFechaP)
                            .addComponent(lblFechaE)
                            .addComponent(lblFechaEntre))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlContenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addComponent(tatFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblItems)
                .addGap(4, 4, 4)
                .addGroup(pnlContenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addGroup(pnlContenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(jLabel8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        jScrollPane1.setViewportView(pnlConten);

        pnlBotones.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        btnAceptar.setMnemonic('A');
        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnCancelar.setMnemonic('C');
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBotonesLayout = new javax.swing.GroupLayout(pnlBotones);
        pnlBotones.setLayout(pnlBotonesLayout);
        pnlBotonesLayout.setHorizontalGroup(
            pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBotonesLayout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(btnAceptar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(38, 38, 38)
                .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                .addGap(130, 130, 130))
        );
        pnlBotonesLayout.setVerticalGroup(
            pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnAceptar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE)
                    .addComponent(pnlBotones, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 567, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
    //Impresion imp = new Impresion(this.pnlConten);
    //imp.imprimir();
        try {
            javax.swing.UIManager.setLookAndFeel("com.birosoft.liquid.LiquidLookAndFeel");
            guardarCompra();
            this.dispose();
            MenuVista.setInternal(33);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        try {
            javax.swing.UIManager.setLookAndFeel("com.birosoft.liquid.LiquidLookAndFeel");
            this.dispose();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        try {
            javax.swing.UIManager.setLookAndFeel("com.birosoft.liquid.LiquidLookAndFeel");
            this.dispose();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_formWindowClosing
    public void establecerValores(String total,String subTotal,String descTotal,String baseGrabable,String IVA,String cambio,String pagaCon){
        this.total = total;
        //this.subTotal = subTotal;
        this.descTotal = descTotal;
        this.baseGrabable = baseGrabable;
        this.IVA = IVA;
        this.cambio =cambio;
        this.pagaCon =pagaCon;
    }
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelFechaPedi;
    private javax.swing.JLabel labelProv;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblEmpresa;
    private javax.swing.JLabel lblFechaE;
    private javax.swing.JLabel lblFechaEntre;
    private javax.swing.JLabel lblFechaP;
    private javax.swing.JLabel lblItems;
    private javax.swing.JLabel lblNIT;
    private javax.swing.JLabel lblProveedor;
    private javax.swing.JLabel lblRazonSocial;
    private javax.swing.JLabel lblUbicacion;
    private javax.swing.JPanel pnlBotones;
    private javax.swing.JPanel pnlConten;
    private javax.swing.JTextArea tatFactura;
    private javax.swing.JTextArea tatImpuesto;
    // End of variables declaration//GEN-END:variables
}
