package vista;

import javax.swing.JRadioButton;

public class PanelInventario extends javax.swing.JPanel {

    FachadaInterfaz fachada;

    public PanelInventario() {
        initComponents();
        fachada = FachadaInterfaz.getInstancia();
        cargarComboProducto();
        cargarComboCategoria();
        habilitarCombo(6, false);
        this.setSize(500, 400);
        this.setVisible(false);
    }

  

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jrbAgotado = new javax.swing.JRadioButton();
        jrFamilia = new javax.swing.JRadioButton();
        jcbFamilia = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        jrCompraProducto = new javax.swing.JRadioButton();
        jrCompraCategoria = new javax.swing.JRadioButton();
        jcbCompraProducto = new javax.swing.JComboBox();
        jcbCompraCategoria = new javax.swing.JComboBox();
        jrEspera = new javax.swing.JRadioButton();
        jrPagos = new javax.swing.JRadioButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Productos Agotados"));

        buttonGroup1.add(jrbAgotado);
        jrbAgotado.setText("Todos");
        jrbAgotado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbAgotadoActionPerformed(evt);
            }
        });

        buttonGroup1.add(jrFamilia);
        jrFamilia.setText("Por Categoria");
        jrFamilia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrFamiliaActionPerformed(evt);
            }
        });

        jcbFamilia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrbAgotado)
                    .addComponent(jrFamilia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbFamilia, 0, 144, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jrbAgotado)
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jcbFamilia, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jrFamilia, javax.swing.GroupLayout.Alignment.LEADING)))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Compras"));

        buttonGroup1.add(jrCompraProducto);
        jrCompraProducto.setText("Por Producto");
        jrCompraProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrCompraProductoActionPerformed(evt);
            }
        });

        buttonGroup1.add(jrCompraCategoria);
        jrCompraCategoria.setText("Por Categoria");
        jrCompraCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrCompraCategoriaActionPerformed(evt);
            }
        });

        jcbCompraProducto.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jcbCompraCategoria.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        buttonGroup2.add(jrEspera);
        jrEspera.setText("EN ESPERA");

        buttonGroup2.add(jrPagos);
        jrPagos.setText("PAGOS");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrCompraProducto)
                    .addComponent(jrCompraCategoria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jcbCompraProducto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jcbCompraCategoria, 0, 134, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrPagos, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                    .addComponent(jrEspera))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jrCompraProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jcbCompraProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jrCompraCategoria)
                            .addComponent(jcbCompraCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jrEspera, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jrPagos)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jrbAgotadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbAgotadoActionPerformed
        this.habilitarCombo(3, false);
    }//GEN-LAST:event_jrbAgotadoActionPerformed

    private void jrFamiliaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrFamiliaActionPerformed
        this.habilitarCombo(5,true);
}//GEN-LAST:event_jrFamiliaActionPerformed

    private void jrCompraProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrCompraProductoActionPerformed
       this.habilitarCombo(3, true);
    }//GEN-LAST:event_jrCompraProductoActionPerformed

    private void jrCompraCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrCompraCategoriaActionPerformed
        this.habilitarCombo(4, true);
    }//GEN-LAST:event_jrCompraCategoriaActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JComboBox jcbCompraCategoria;
    private javax.swing.JComboBox jcbCompraProducto;
    private javax.swing.JComboBox jcbFamilia;
    public javax.swing.JRadioButton jrCompraCategoria;
    public javax.swing.JRadioButton jrCompraProducto;
    public javax.swing.JRadioButton jrEspera;
    public javax.swing.JRadioButton jrFamilia;
    public javax.swing.JRadioButton jrPagos;
    public javax.swing.JRadioButton jrbAgotado;
    // End of variables declaration//GEN-END:variables

    public void cargarComboProducto() {

        this.jcbCompraProducto.setModel(new ModeloCombo(fachada.getProductos()));
        this.jcbCompraProducto.getModel().setSelectedItem("Seleccione Un Producto");
    }

    public void cargarComboCategoria() {
   
        this.jcbFamilia.setModel(new ModeloCombo(fachada.getCategoria()));
        this.jcbFamilia.getModel().setSelectedItem("Seleccione Una Categoria...");
        this.jcbCompraCategoria.setModel(new ModeloCombo(fachada.getCategoria()));
        this.jcbCompraCategoria.getModel().setSelectedItem("Seleccione Una Categoria...");
    }

    public String getCodigo(int tipo) {
        String codigo = null;
        switch (tipo) {
            case 3:
                codigo = (String) ((ModeloCombo) jcbFamilia.getModel()).getSelectedIndex();
                break;
            case 4:
                codigo = (String) ((ModeloCombo) this.jcbCompraCategoria.getModel()).getSelectedIndex();
                break;
            case 5:
                codigo = (String) ((ModeloCombo) this.jcbCompraProducto.getModel()).getSelectedIndex();
                break;
        }
        return codigo;
    }

    public void habilitarCombo(int tipo, boolean b) {
        switch (tipo) {
            case 1:
      
                this.jcbCompraCategoria.setEnabled(false);
                this.jcbCompraProducto.setEnabled(false);
                this.jcbFamilia.setEnabled(false);
                break;
            case 2:
  
                this.jcbCompraCategoria.setEnabled(false);
                this.jcbCompraProducto.setEnabled(false);
                this.jcbFamilia.setEnabled(false);
                break;
            case 3:
      
                this.jcbCompraCategoria.setEnabled(false);
                this.jcbFamilia.setEnabled(false);
                this.jcbCompraProducto.setEnabled(b);
                break;
            case 4:
    
                this.jcbCompraCategoria.setEnabled(b);
                this.jcbCompraProducto.setEnabled(false);
                this.jcbFamilia.setEnabled(false);
                break;
            case 5:
                this.jcbCompraCategoria.setEnabled(false);
                this.jcbCompraProducto.setEnabled(false);
                this.jcbFamilia.setEnabled(b);
                break;
            case 6:
                this.jcbCompraCategoria.setEnabled(false);
                this.jcbCompraProducto.setEnabled(false);
                this.jcbFamilia.setEnabled(false);
                break;

        }
    }
}
