package vista;

import control.ObservadorEventos;
import java.util.List;
import java.util.Map;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JRadioButton;

/**
 *
 * @author Kymera Systems SAS
 */
public class PanelBusqueda extends javax.swing.JPanel implements ObservadorEventos {

    public static final int PRODUCTO = 1;
    public static final int PERSONAL = 2;
    public static final int PROVEEDOR = 4;
    public static final int CLIENTE = 3;
    private static String buscar = "";
    private FachadaInterfaz fachada;

    public PanelBusqueda() {
        initComponents();
        fachada = FachadaInterfaz.getInstancia();
        fachada.ptoVenta.removeEscuchadorEventos(this);
        fachada.ptoVenta.addEscuchadorEventos(this);
        cargarComboCategoria();
        habilitarCombo(false);
        this.setSize(300, 100);
        this.setVisible(false);

    }

    public JRadioButton getJrEspecificar() {
        return jrEspecificar;
    }

    public JRadioButton getJrTodos() {
        return jrTodos;
    }

    public JComboBox getJcbCategoria() {
        return jcbCategoria;
    }

    public JRadioButton getJrCategoria() {
        return jrCategoria;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jrTodos = new javax.swing.JRadioButton();
        jrEspecificar = new javax.swing.JRadioButton();
        lblCodigo = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        jrCategoria = new javax.swing.JRadioButton();
        jcbCategoria = new javax.swing.JComboBox();

        buttonGroup1.add(jrTodos);
        jrTodos.setText("Todos");
        jrTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrTodosActionPerformed(evt);
            }
        });

        buttonGroup1.add(jrEspecificar);
        jrEspecificar.setText("Especificar");
        jrEspecificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrEspecificarActionPerformed(evt);
            }
        });

        lblCodigo.setForeground(new java.awt.Color(204, 0, 0));

        lblNombre.setForeground(new java.awt.Color(204, 0, 0));

        buttonGroup1.add(jrCategoria);
        jrCategoria.setText("Por Categoria");

        jcbCategoria.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jrEspecificar)
                            .addComponent(jrCategoria))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE))
                            .addComponent(jcbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jrTodos))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jrTodos)
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblNombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCodigo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jrEspecificar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jrCategoria)
                    .addComponent(jcbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(70, 70, 70))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jrTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrTodosActionPerformed
    }//GEN-LAST:event_jrTodosActionPerformed

    private void jrEspecificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrEspecificarActionPerformed

        if (buscar.equals("producto")) {
            new BuscarProdVista(MenuVista.getInstancia());
        } else if (buscar.equals("proveedor")) {
            new BuscarProvVista(MenuVista.getInstancia());
        } else if (buscar.equals("personal")) {
            new BuscarPersonal(MenuVista.getInstancia());
        } else if (buscar.equals("cliente")) {
            new BuscarClienteVista(MenuVista.getInstancia());
        }

    }//GEN-LAST:event_jrEspecificarActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox jcbCategoria;
    private javax.swing.JRadioButton jrCategoria;
    private javax.swing.JRadioButton jrEspecificar;
    private javax.swing.JRadioButton jrTodos;
    public javax.swing.JLabel lblCodigo;
    public javax.swing.JLabel lblNombre;
    // End of variables declaration//GEN-END:variables

    public void cargar(int tipo) {
        switch (tipo) {
            case PRODUCTO:
                buscar = "producto";
                habilitarCombo(true);
                break;
            case PROVEEDOR:

                buscar = "proveedor";
                 habilitarCombo(false);
                break;
            case PERSONAL:

                buscar = "personal";
                 habilitarCombo(false);
                break;
            case CLIENTE:

                buscar = "cliente";
                 habilitarCombo(false);
                break;
        }
    }
    public void cargarComboCategoria(){
        jcbCategoria.setModel(new ModeloCombo(fachada.getCategoria()));
    }
    public void habilitarCombo(boolean b){
        jcbCategoria.setVisible(b);
        jcbCategoria.setEnabled(b);
        jrCategoria.setVisible(b);
     
    }

    public String obtenerID(){
        return lblCodigo.getText();
    }
    public String obtenerIDcategoria(){
        return (String) ((ModeloCombo)jcbCategoria.getModel()).getSelectedIndex();
    }

    public void escuchadorEvento(Object obj, String propiedad, Object valor) {
        if (propiedad.equals(control.PuntoDeVenta.DATOS_PER_ENCON)) {
            List dato = (List) valor;
             lblCodigo.setText(dato.get(0).toString());
             lblNombre.setText(dato.get(1).toString());
        }else if(propiedad.equals(control.PuntoDeVenta.DATOS_PRO_ENCON)){
             List dato = (List) valor;
             lblCodigo.setText(dato.get(0).toString());
             lblNombre.setText(dato.get(1).toString());
        }else if(propiedad.equals(control.PuntoDeVenta.DATOS_PRV_ENCON)){
             List dato = (List) valor;
             lblCodigo.setText(dato.get(0).toString());
             lblNombre.setText(dato.get(1).toString());
        }else if(propiedad.equals(control.PuntoDeVenta.CLIENTE_VENTA)){
             List dato = (List) valor;
             lblCodigo.setText(dato.get(0).toString());
             lblNombre.setText(dato.get(1).toString());
        }
    }
}
