/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelGraficas.java
 *
 * Created on 20-mar-2010, 8:24:17
 */
package vista;

import javax.swing.JComboBox;
import javax.swing.JRadioButton;

/**
 *
 * @author Alejandro
 */
public class PanelGraficas extends javax.swing.JPanel {

    /** Creates new form PanelGraficas */
    public PanelGraficas() {
        initComponents();
        cargarComboAño();
        habilitarCombo(1, false);
        this.setSize(300, 300);
        this.setVisible(false);
    }

    public JComboBox getJcbAñoDesde() {
        return jcbAñoDesde;
    }

    public JComboBox getJcbAñoHasta() {
        return jcbAñoHasta;
    }

    public JRadioButton getJrAño() {
        return jrAño;
    }

    public JRadioButton getJrMensual() {
        return jrMensual;
    }

    public JRadioButton getJrDiaria() {
        return jrDiaria;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jrDiaria = new javax.swing.JRadioButton();
        jrMensual = new javax.swing.JRadioButton();
        jcbMes = new javax.swing.JComboBox();
        jcbAño = new javax.swing.JComboBox();
        jrAño = new javax.swing.JRadioButton();
        jcbAñoDesde = new javax.swing.JComboBox();
        jcbAñoHasta = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        buttonGroup1.add(jrDiaria);
        jrDiaria.setText("Grafica Mensual");
        jrDiaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrDiariaActionPerformed(evt);
            }
        });

        buttonGroup1.add(jrMensual);
        jrMensual.setText("Grafica Anual");
        jrMensual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrMensualActionPerformed(evt);
            }
        });

        jcbMes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione Un Mes", "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));
        jcbMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbMesActionPerformed(evt);
            }
        });

        jcbAño.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecciones Un Año" }));
        jcbAño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbAñoActionPerformed(evt);
            }
        });

        buttonGroup1.add(jrAño);
        jrAño.setText("Grafica Año x Año");
        jrAño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrAñoActionPerformed(evt);
            }
        });

        jLabel1.setText("Fecha Desde");

        jLabel2.setText("Fecha Hasta");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jrDiaria)
                        .addGap(18, 18, 18)
                        .addComponent(jcbMes, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jrMensual)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jcbAño, 0, 162, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jrAño)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jcbAñoHasta, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jcbAñoDesde, javax.swing.GroupLayout.Alignment.LEADING, 0, 96, Short.MAX_VALUE))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrDiaria)
                    .addComponent(jcbMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrMensual)
                    .addComponent(jcbAño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jrAño)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jcbAñoDesde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbAñoHasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(124, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jrMensualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrMensualActionPerformed
        habilitarCombo(2, true);
    }//GEN-LAST:event_jrMensualActionPerformed

    private void jcbAñoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbAñoActionPerformed
        obtenerAño();
    }//GEN-LAST:event_jcbAñoActionPerformed

    private void jrDiariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrDiariaActionPerformed
        habilitarCombo(1, true);
    }//GEN-LAST:event_jrDiariaActionPerformed

    private void jrAñoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrAñoActionPerformed
         habilitarCombo(3, true);
    }//GEN-LAST:event_jrAñoActionPerformed

    private void jcbMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbMesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbMesActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JComboBox jcbAño;
    private javax.swing.JComboBox jcbAñoDesde;
    private javax.swing.JComboBox jcbAñoHasta;
    private javax.swing.JComboBox jcbMes;
    private javax.swing.JRadioButton jrAño;
    private javax.swing.JRadioButton jrDiaria;
    private javax.swing.JRadioButton jrMensual;
    // End of variables declaration//GEN-END:variables

    public String obtenerMes() {
        String cod;
        int i = this.jcbMes.getSelectedIndex();
        return cod = String.valueOf(i);
    }

    public String obtenerAño() {
        return this.jcbAño.getSelectedItem().toString();
    }

    public void cargarComboAño() {
        int year = utilidades.Utilidades.getAñoActual();
        for (int i = 2000; i <= year; i++) {
            this.jcbAño.addItem(i);
            this.jcbAñoDesde.addItem(i);
            this.jcbAñoHasta.addItem(i);
        }
    }

    public void habilitarCombo(int tipo, boolean b) {
        switch (tipo) {
            case 1:
                this.jcbMes.setEnabled(b);
                this.jcbAño.setEnabled(false);
                this.jcbAñoDesde.setEnabled(false);
                this.jcbAñoHasta.setEnabled(false);
                break;
            case 2:
                this.jcbMes.setEnabled(false);
                this.jcbAñoDesde.setEnabled(false);
                this.jcbAñoHasta.setEnabled(false);
                this.jcbAño.setEnabled(b);
                break;
            case 3: {
                this.jcbMes.setEnabled(false);
                this.jcbAñoDesde.setEnabled(b);
                this.jcbAñoHasta.setEnabled(b);
                this.jcbAño.setEnabled(false);
                break;
            }
        }
    }
}
