/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Tiquete.java
 *
 * Created on 27-may-2010, 17:27:09
 */

package vista;

/**
 *
 * @author Juan Fernando
 */
public class Tiquete extends javax.swing.JDialog {

    /** Creates new form Tiquete */
    public Tiquete(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jTextArea12 = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        jTextArea13 = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        lblUbicacion1 = new javax.swing.JLabel();
        lblDireccion9 = new javax.swing.JLabel();
        lblNIT1 = new javax.swing.JLabel();
        lblEmpresa1 = new javax.swing.JLabel();
        lblDireccion10 = new javax.swing.JLabel();
        lblDireccion11 = new javax.swing.JLabel();
        lblDireccion12 = new javax.swing.JLabel();
        lblDireccion13 = new javax.swing.JLabel();
        lblDireccion14 = new javax.swing.JLabel();
        lblDireccion15 = new javax.swing.JLabel();
        lblDireccion16 = new javax.swing.JLabel();
        jTextArea14 = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();
        jTextArea15 = new javax.swing.JTextArea();
        jLabel15 = new javax.swing.JLabel();
        lblDireccion17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        lblRazonSocial1 = new javax.swing.JLabel();
        jTextArea16 = new javax.swing.JTextArea();
        jTextArea17 = new javax.swing.JTextArea();
        jLabel18 = new javax.swing.JLabel();
        jTextArea18 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTextArea12.setColumns(20);
        jTextArea12.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        jTextArea12.setRows(5);
        jTextArea12.setText("==========");

        jLabel12.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        jLabel12.setText("Descuento:");

        jTextArea13.setColumns(20);
        jTextArea13.setFont(new java.awt.Font("Arial", 0, 10));
        jTextArea13.setRows(5);
        jTextArea13.setText("$123.000.00");

        jLabel13.setFont(new java.awt.Font("Arial", 0, 10));
        jLabel13.setText("Descuento:");

        lblUbicacion1.setFont(new java.awt.Font("Arial", 0, 10));
        lblUbicacion1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUbicacion1.setText("UBICACION");

        lblDireccion9.setFont(new java.awt.Font("Arial", 0, 10));
        lblDireccion9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDireccion9.setText("DIRECCION");

        lblNIT1.setFont(new java.awt.Font("Arial", 0, 10));
        lblNIT1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNIT1.setText("NIT");

        lblEmpresa1.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        lblEmpresa1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEmpresa1.setText("EMPRESA");

        lblDireccion10.setFont(new java.awt.Font("Arial", 0, 10));
        lblDireccion10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDireccion10.setText("ALEJANDRO SARMIENTO");

        lblDireccion11.setFont(new java.awt.Font("Arial", 0, 10));
        lblDireccion11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDireccion11.setText("HECTOR SANCHEZ");

        lblDireccion12.setFont(new java.awt.Font("Arial", 0, 10));
        lblDireccion12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDireccion12.setText("Cajero");

        lblDireccion13.setFont(new java.awt.Font("Arial", 0, 10));
        lblDireccion13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDireccion13.setText("Cliente");

        lblDireccion14.setFont(new java.awt.Font("Arial", 0, 10));
        lblDireccion14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDireccion14.setText("Tiquete");

        lblDireccion15.setFont(new java.awt.Font("Arial", 0, 10));
        lblDireccion15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDireccion15.setText("FECHA");

        lblDireccion16.setFont(new java.awt.Font("Arial", 0, 10));
        lblDireccion16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDireccion16.setText("HORA");

        jTextArea14.setColumns(20);
        jTextArea14.setFont(new java.awt.Font("Arial", 0, 10));
        jTextArea14.setRows(5);

        jLabel14.setFont(new java.awt.Font("Arial", 0, 10));
        jLabel14.setText("SUBTOTAL");

        jTextArea15.setColumns(20);
        jTextArea15.setFont(new java.awt.Font("Arial", 0, 10));
        jTextArea15.setRows(5);

        jLabel15.setFont(new java.awt.Font("Arial", 0, 10));
        jLabel15.setText("PRODUCTO");

        lblDireccion17.setFont(new java.awt.Font("Arial", 0, 10));
        lblDireccion17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDireccion17.setText("IBA001-0007");

        jLabel16.setFont(new java.awt.Font("Arial", 0, 10));
        jLabel16.setText("PRECIO UNI");

        jLabel17.setFont(new java.awt.Font("Arial", 0, 10));
        jLabel17.setText("CANT");

        lblRazonSocial1.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        lblRazonSocial1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRazonSocial1.setText("RAZON SOCIAL");

        jTextArea16.setColumns(20);
        jTextArea16.setFont(new java.awt.Font("Arial", 0, 10));
        jTextArea16.setRows(5);

        jTextArea17.setColumns(20);
        jTextArea17.setFont(new java.awt.Font("Arial", 0, 10));
        jTextArea17.setRows(5);

        jLabel18.setFont(new java.awt.Font("Arial", 0, 10));
        jLabel18.setText("Subtotal sin Descuento:");

        jTextArea18.setColumns(20);
        jTextArea18.setFont(new java.awt.Font("Arial", 0, 10));
        jTextArea18.setRows(5);
        jTextArea18.setText("$123.000.00");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jTextArea14, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextArea15, 0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(56, 56, 56)
                                .addComponent(jLabel17)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel16)
                            .addComponent(jTextArea16, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel18)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextArea18, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                    .addComponent(jLabel14)
                    .addComponent(jTextArea17, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                    .addComponent(jTextArea13, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                    .addComponent(jTextArea12, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE))
                .addGap(4, 4, 4))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblDireccion12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblDireccion13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addComponent(lblDireccion14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblDireccion11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblDireccion10, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                    .addComponent(lblDireccion17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDireccion15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDireccion16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                .addComponent(lblDireccion9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblUbicacion1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblEmpresa1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblNIT1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblRazonSocial1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(lblRazonSocial1)
                .addGap(1, 1, 1)
                .addComponent(lblNIT1)
                .addGap(1, 1, 1)
                .addComponent(lblEmpresa1)
                .addGap(1, 1, 1)
                .addComponent(lblUbicacion1)
                .addGap(1, 1, 1)
                .addComponent(lblDireccion9)
                .addGap(1, 1, 1)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblDireccion12)
                        .addGap(1, 1, 1)
                        .addComponent(lblDireccion13)
                        .addGap(1, 1, 1)
                        .addComponent(lblDireccion14))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblDireccion10)
                        .addGap(1, 1, 1)
                        .addComponent(lblDireccion11)
                        .addGap(1, 1, 1)
                        .addComponent(lblDireccion17))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblDireccion15)
                        .addGap(1, 1, 1)
                        .addComponent(lblDireccion16)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextArea14, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextArea15, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTextArea17, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextArea18, 0, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextArea13, 0, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextArea12, 0, 0, Short.MAX_VALUE))
                    .addComponent(jTextArea16, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1042, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextArea jTextArea12;
    private javax.swing.JTextArea jTextArea13;
    private javax.swing.JTextArea jTextArea14;
    private javax.swing.JTextArea jTextArea15;
    private javax.swing.JTextArea jTextArea16;
    private javax.swing.JTextArea jTextArea17;
    private javax.swing.JTextArea jTextArea18;
    private javax.swing.JLabel lblDireccion10;
    private javax.swing.JLabel lblDireccion11;
    private javax.swing.JLabel lblDireccion12;
    private javax.swing.JLabel lblDireccion13;
    private javax.swing.JLabel lblDireccion14;
    private javax.swing.JLabel lblDireccion15;
    private javax.swing.JLabel lblDireccion16;
    private javax.swing.JLabel lblDireccion17;
    private javax.swing.JLabel lblDireccion9;
    private javax.swing.JLabel lblEmpresa1;
    private javax.swing.JLabel lblNIT1;
    private javax.swing.JLabel lblRazonSocial1;
    private javax.swing.JLabel lblUbicacion1;
    // End of variables declaration//GEN-END:variables

}
